{
 "title": "Kube Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "email", "query": { "query": "label_values(email)" } },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase,cluster) (kube_pod_status_phase{cluster=\"$cluster\", email=\"$email\"})",
     "legendFormat": "{{cluster}}-{{phase}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{cluster=\"$cluster\", email=\"$email\"}) by (pod,cluster)",
     "legendFormat": "{{cluster}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition,cluster) (kube_node_status_condition{status=\"true\",cluster=\"$cluster\", email=\"$email\"})",
     "legendFormat": "{{cluster}}-{{condition}}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster=\"$cluster\", email=\"$email\"}) by (deployment,cluster)",
     "legendFormat": "{{cluster}}-{{deployment}}"
    }
   ]
  },
  {
   "title": "PV Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase,cluster) (kube_persistentvolume_status_phase{cluster=\"$cluster\", email=\"$email\"})",
     "legendFormat": "{{cluster}}-{{phase}}"
    }
   ]
  }
 ]
}