{
 "title": "Node Exporter Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "email", "query": { "query": "label_values(email)" } },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(instance,cluster) (rate(node_cpu_seconds_total{mode='idle',cluster=\"$cluster\",email=\"$email\"}[5m]))",
     "legendFormat": "{{cluster}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{cluster=\"$cluster\", email=\"$email\"}",
     "legendFormat": "{{cluster}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\", email=\"$email\"}[5m])",
     "legendFormat": "{{cluster}}-{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\", email=\"$email\"}[5m])",
     "legendFormat": "{{cluster}}-{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{ fstype!~\"tmpfs|squashfs\",cluster=\"$cluster\", email=\"$email\"}",
     "legendFormat": "{{cluster}}-{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{cluster=\"$cluster\", email=\"$email\"}[5m])",
     "legendFormat": "{{cluster}}-{{instance}} {{device}}"
    }
   ]
  }
 ]
}