{
 "title": "API Server Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Server Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{}[5m])) by (code,cluster,email)",
     "legendFormat": "{{cluster}}-{{code}} #{{email}}"
    }
   ]
  },
  {
   "title": "API Server Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{}[5m])) by (le,cluster,email))",
     "legendFormat": "{{cluster}}-99th percentile #{{email}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(apiserver_request_duration_seconds_bucket{}[5m])) by (le,cluster,email))",
     "legendFormat": "{{cluster}}-50th percentile #{{email}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "workqueue_depth{}",
     "legendFormat": "{{cluster}}-{{name}} #{{email}}"
    }
   ]
  },
  {
   "title": "ETCD Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le, operation,cluster, email))",
     "legendFormat": "{{cluster}} - 99th percentile - {{operation}} #{{email}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le, operation,cluster,email))",
     "legendFormat": "{{cluster}} - 50th percentile - {{operation}}#{{email}}"
    },
    {
     "expr": "sum(rate(etcd_request_duration_seconds_sum[5m])) by (operation) / sum(rate(etcd_request_duration_seconds_count[5m])) by (operation,cluster, email)",
     "legendFormat": "{{cluster}} - average - {{operation}}#{{email}}"
    }
   ]
  }
 ]
}