{
 "title": "Kube Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (phase,cluster,email) (kube_pod_status_phase{})",
     "legendFormat": "{{cluster}}-{{phase}}#{{email}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{}) by (pod,cluster,email)",
     "legendFormat": "{{cluster}}-{{pod}}#{{email}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (condition, cluster, email) (kube_node_status_condition{status=\"true\"})",
     "legendFormat": "{{cluster}}-{{condition}}#{{email}}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{}) by (deployment,cluster,email)",
     "legendFormat": "{{cluster}}-{{deployment}}#{{email}}"
    }
   ]
  },
  {
   "title": "PV Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (phase,cluster,email) (kube_persistentvolume_status_phase{})",
     "legendFormat": "{{cluster}}-{{phase}}#email"
    }
   ]
  }
 ]
}